```{r}
#install.packages("googlesheets")
library(googlesheets)

#install.packages("tidyverse")
#install.packages("readr")
library(tidyverse)
library(dplyr)
library("curl")
library(readr)

gs_ls()

```

make new columns
```{r}
# read in all the google sheets data
wildfilm <- gs_title("Wildfilm spreadsheet")
media_data <- wildfilm %>% gs_read(ws="media",col_types = cols(species = col_character()))
media_data <- filter(media_data,complete == "Y")
media_data <- arrange(media_data,desc(date))

creators_data <- wildfilm %>% gs_read(ws="creators")
creators_data <- filter(creators_data,!is.na(creator_name))

species_data <- wildfilm %>% gs_read(ws="species")
species_data <- filter(species_data,!is.na(common_name))
series_data <- wildfilm %>% gs_read(ws="series")

# make data more readable, add new columns etc
yt_image_template <- c("https://i1.ytimg.com/vi/insert_video_id/mqdefault.jpg")
yt_media_template <- c("//www.youtube.com/watch?v=insert_video_id")

media_data <- left_join(media_data,series_data, by=c("series_id"="id"))
media_data <- left_join(media_data,creators_data, by=c("creator_id"="id"))

media_data <- mutate(media_data,ser_url = paste0("<a href='creators/",creator_id,".html#",series_id,"'>",series,"</a>"))

#videos
for(i in 1:nrow(media_data)){
  print(i)
  if(media_data$format[i] == "V"){
    media_data$image_url[i] <- gsub("insert_video_id",media_data$video_id[i],yt_image_template)
    
    media_data$media_url[i] <- gsub("insert_video_id",media_data$video_id[i],yt_media_template)
    media_data$media_icon[i] <- "play-circle"
    media_data$media_type[i] <- "Video"
  } else if (media_data$format[i] == "P"){
    media_data$media_icon[i] <- "headphones"
    media_data$media_type[i] <- "Podcast"
  } else if (media_data$format[i] == "P"){
    media_data$media_icon[i] <- "font"
    media_data$media_type[i] <- "Blog post"
  }
  
  the_date <- unlist(strsplit(media_data$date[i],"/"))
  
  media_data$t_date[i] <- paste(month.abb[as.numeric(the_date[2])],the_date[1])
  
  if (grepl("NA", media_data$ser_url[i])){
    media_data$ser_url[i] <- NA
  }
  
}





```


make homepage
```{r}



page <- readLines("index_template.html")
page <- paste(page, collapse = '')
  
media_template <- gsub(".*START|END.*", "", page)
page <- gsub( " *\\START.*?\\END *", "insert_medias",page)

medias <- ""

for(i in 1:nrow(media_data)){
  media_temp <- media_template
  
  #do all the normal fields, as long as it's not NA
  for (ii in 1:ncol(media_data)){
    field <- colnames(media_data)[ii]
    if (!is.na(media_data[i,ii])){
      media_temp <- gsub(paste("insert",field,sep = "_"),
           media_data[i,ii],
           media_temp)
    }
  }
  
  #remove seriesinformation if it's not actually for a series
  media_temp <- 
    gsub("<p class='vid-title'><small><b>insert_ser_url \\(insert_episode_num/insert_num_of_eps\\)</b> </small></p>",
       "",
       media_temp)
  
  # species lists
  medias_species <- unlist(strsplit(as.character(media_data$species[i]),","))
  species_html <- "Featuring: "
  species_template <- "<a href='https://en.wikipedia.org/wiki/insert_scientific_name' data-lity>insert_common_name (<i>insert_scientific_name</i>)</a>"
    
  if (!is.na(medias_species)){
    
    
    for (ii in 1:length(medias_species)){
      ii_now <- as.numeric(medias_species)[ii]
      this_species <- species_template
      this_species <- gsub("insert_common_name",
           species_data$common_name[ii_now],
           this_species)
      this_species <- gsub("insert_scientific_name",
           species_data$scientific_name[ii_now],
           this_species)
      
      # add a comma or a full stop
      if (ii != length(medias_species)) {
        this_species <- paste(this_species,", ",sep = "")
      } else {
        this_species <- paste(this_species,".",sep = "")
      }
      
      species_html <- paste(species_html,this_species,sep = "")
    }
    
    media_temp <- gsub("insert_list_species",
       species_html,
       media_temp)
  } else {
    media_temp <- gsub("<p><small>insert_list_species</small></p>",
       "",
       media_temp)
  }
  
  
  
  
  

  
  medias <- paste(medias,media_temp)
}

# species
species_list <- ""

for (i in 1:nrow(species_data)){
  species_list <- paste(species_list,'"',species_data$common_name[i]," (<i>",species_data$scientific_name[i],'</i>)"',sep = "")
  
  species_list <- paste(species_list,",")

}

for (i in 1:nrow(creators_data)){
  species_list <- paste(species_list,'"',creators_data$creator_name[i],'"',sep = "")
  if (i < nrow(creators_data)){
    species_list <- paste(species_list,",")
  }
}

page <- gsub("insert_medias",medias,page)
page <- gsub("insert_update_date",Sys.Date(),page)
page <- gsub("insert_species_list",species_list,page)
write(page,file = "index.html")
 
```

make author page

```{r}

media_data <- arrange(media_data,series_id,episode_num,desc(date))

for (i in creators_data$id){
  new_series <- ""
  page <- readLines("creator_template.html")
  page <- paste(page, collapse = '')
  
  media_template <- gsub(".*START|END.*", "", page)
  page <- gsub( " *\\START.*?\\END *", "insert_medias",page)
  medias <- ""
  this_creator <- filter(creators_data, id == i)
  
  media_links <- ""
  
  #make youtube button
  if (!is.na(this_creator$youtube)){
    media_links <- paste0(media_links,'<div class="g-ytsubscribe" data-channelid="',this_creator$youtube,'" data-layout="default" data-count="default"></div>')
  }
  
  #make twitter button
  if (!is.na(this_creator$twitter)){
    media_links <- paste0(media_links,' <a href="https://twitter.com/',this_creator$twitter,'" class="twitter-follow-button" data-show-count="false">Follow</a>')
  }
  
  print(media_links)
  
  if (media_links != ""){
    page <- gsub("insert_media_links",media_links,page)
  } else {
    page <- gsub("insert_media_links","",page)
  }
  
  # sub creator bio stuff
  for (ii in 1:ncol(this_creator)){
    field <- colnames(this_creator)[ii]
    if (!is.na(this_creator[ii])){
      page <- gsub(paste("insert",field,sep = "_"),
                   this_creator[ii],
                   page)
    } else {
      page <- gsub(paste("insert",field,sep = "_"),
                   "",
                   page)
    }
    
  }
  
  
  
  for(j in (1:nrow(media_data))[media_data$creator_id == i]){

    media_temp <- media_template
    
    #do all the normal fields, as long as it's not NA
    for (ii in 1:ncol(media_data)){
      field <- colnames(media_data)[ii]
      if (!is.na(media_data[j,ii])){
        media_temp <- gsub(paste("insert",field,sep = "_"),
                           media_data[j,ii],
                           media_temp)
      }
    }
    
    # species lists
    medias_species <- unlist(strsplit(as.character(media_data$species[j]),","))
    species_html <- "Featuring: "
    species_template <- "<a href='https://en.wikipedia.org/wiki/insert_scientific_name' data-lity>insert_common_name (<i>insert_scientific_name</i>)</a>"
    
    if (!is.na(medias_species)){
      
      
      for (ii in 1:length(medias_species)){
        ii_now <- as.numeric(medias_species)[ii]
        this_species <- species_template
        this_species <- gsub("insert_common_name",
                             species_data$common_name[ii_now],
                             this_species)
        this_species <- gsub("insert_scientific_name",
                             species_data$scientific_name[ii_now],
                             this_species)
        
        if (ii != length(medias_species)) {
          this_species <- paste(this_species,", ",sep = "")
        } else {
          this_species <- paste(this_species,".",sep = "")
        }
        
        species_html <- paste(species_html,this_species,sep = "")
      }
      
      media_temp <- gsub("insert_list_species",
                         species_html,
                         media_temp)
    } else {
      media_temp <- gsub("<p><small>insert_list_species</small></p>",
                         "",
                         media_temp)
    }
    
    
    
    
    
    
    if (!is.na(media_data$series[j])){
      if (new_series != media_data$series[j]){
        medias <- paste0(medias,"<a id=",media_data$series_id[j],"><h3>",media_data$series[j]," <small>(",media_data$num_of_eps[j]," Episodes)</small></h3></a><p>",media_data$series_description[j],"</p>")
        new_series<- media_data$series[j]
      }
    }
    medias <- paste(medias,media_temp)
  }
  
  page <- gsub("insert_medias",medias,page)
  page <- gsub("insert_update_date",Sys.Date(),page)
  write(page,file = paste0("creators/",this_creator$id,".html"))
  
}







```





